# Generated by Django 3.1.4 on 2021-01-16 16:33

import assignments.models.assignment_model
from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20210116_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(upload_to=assignments.models.assignment_model.upload_path),
        ),
    ]
