# Generated by Django 3.1.4 on 2021-01-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20210119_0746'),
        ('assignments', '0007_auto_20210116_2203'),
    ]

    operations = [
    ]
