# Generated by Django 3.1.4 on 2021-01-31 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentquizdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_status', models.BooleanField(null=True)),
                ('quiz_answers', models.JSONField()),
                ('quizid', models.ForeignKey(db_column='quizid', default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.quizdetails', to_field='quizid')),
                ('studentid', models.ForeignKey(db_column='studentid', default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.studentdetails', to_field='studentid')),
            ],
        ),
        migrations.AddField(
            model_name='quizdetails',
            name='sessionid',
            field=models.ForeignKey(db_column='sessionid', default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.session', to_field='sessionid'),
        ),
        migrations.CreateModel(
            name='Quiz_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question_answers', models.JSONField()),
                ('quizid', models.ForeignKey(db_column='quizid', default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.quizdetails', to_field='quizid')),
            ],
        ),
    ]
