# Generated by Django 3.1.4 on 2021-01-09 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyStudent',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='test@example.com', max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DummyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('max_mark', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(30000.0), django.core.validators.MinValueValidator(-10000.0)])),
                ('alloted_mark', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(30000.0), django.core.validators.MinValueValidator(-10000.0)])),
                ('grade', models.CharField(default='F', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.dummystudent')),
            ],
        ),
    ]
