# Generated by Django 3.1.4 on 2020-12-28 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
