# Generated by Django 3.1.4 on 2021-01-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
