# Generated by Django 3.1.4 on 2021-01-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subscribed',
            new_name='published',
        ),
    ]
