# Generated by Django 3.1.4 on 2021-01-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20210101_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
