# Generated by Django 3.1.4 on 2021-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
