# Generated by Django 3.1.4 on 2021-01-13 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0006_auto_20210113_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.CharField(choices=[('IMMEDIATE', 'Notify Immediately'), ('DAILY', 'Daily Summary'), ('WEEK', 'Weekly Summary'), ('OFF', 'Notification Off')], default='OFF', max_length=32)),
                ('grading_policies', models.CharField(choices=[('IMMEDIATE', 'Notify Immediately'), ('DAILY', 'Daily Summary'), ('WEEK', 'Weekly Summary'), ('OFF', 'Notification Off')], default='OFF', max_length=32)),
                ('course_content', models.CharField(choices=[('IMMEDIATE', 'Notify Immediately'), ('DAILY', 'Daily Summary'), ('WEEK', 'Weekly Summary'), ('OFF', 'Notification Off')], default='OFF', max_length=32)),
                ('files', models.CharField(choices=[('IMMEDIATE', 'Notify Immediately'), ('DAILY', 'Daily Summary'), ('WEEK', 'Weekly Summary'), ('OFF', 'Notification Off')], default='OFF', max_length=32)),
                ('announcement', models.CharField(choices=[('IMMEDIATE', 'Notify Immediately'), ('DAILY', 'Daily Summary'), ('WEEK', 'Weekly Summary'), ('OFF', 'Notification Off')], default='OFF', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificationsetting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
