# Generated by Django 3.1.4 on 2021-01-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='student',
        ),
    ]
