# Generated by Django 3.1.4 on 2021-01-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_email_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='course',
        ),
        migrations.RemoveField(
            model_name='file',
            name='modified_by',
        ),
    ]
