# Generated by Django 3.1.4 on 2021-01-18 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0009_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
