# Generated by Django 3.1.4 on 2021-01-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_auto_20210118_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.assignment'),
        ),
    ]
