# Generated by Django 3.1.4 on 2021-01-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20210121_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.section'),
        ),
    ]
