# Generated by Django 3.1.4 on 2021-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='course_thumbnails'),
        ),
    ]
