# Generated by Django 3.1.4 on 2021-01-25 09:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields
import lms.models.assignment_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0019_auto_20210124_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='display_grades',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('complete/Incomplete', 'Complete/Incomplete'), ('points', 'Points'), ('letter grade', 'Letter Grade'), ('GPA scale', 'GPA Scale'), ('not graded', 'Not Graded')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(null=True, upload_to=lms.models.assignment_model.upload_path),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sub_type',
            field=models.CharField(choices=[('no submission', 'No  Submission'), ('online', 'Online'), ('on paper', 'On Paper'), ('external tool', 'External Tool')], default='no submission', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lms.assignment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
