# Generated by Django 3.1.4 on 2021-01-25 09:46

from django.db import migrations
import image_optimizer.fields
import lms.models.assignment_model


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_auto_20210125_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=lms.models.assignment_model.upload_path),
        ),
    ]
