# Generated by Django 3.1.4 on 2021-01-27 08:45

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0021_auto_20210125_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontype', models.CharField(choices=[('Multiple choice', 'MCQ'), ('Multiple correct', 'MCC'), ('True or False', 'T/F')], default='Multiple choice', max_length=100)),
                ('question', models.TextField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('answer', models.IntegerField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(blank=True, default=5)),
                ('img', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='pics')),
                ('files', models.FileField(blank=True, max_length=254, upload_to='Quiz/uploads')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quizname', models.CharField(max_length=250, unique=True)),
                ('Quiztype', models.CharField(default='Graded Quiz', max_length=100)),
                ('chooseview', models.CharField(blank=True, choices=[('All question at a time', 'All at once'), ('One question at a time', 'One at once')], max_length=100)),
                ('Availablefrom', models.DateTimeField(blank=True)),
                ('Until', models.DateTimeField(blank=True)),
                ('points', models.IntegerField(blank=True)),
                ('Questions', models.IntegerField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=10)),
                ('number_of_attempts', models.IntegerField(default=2)),
                ('Attempts_left', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontype', models.CharField(choices=[('Multiple choice', 'MCQ'), ('Multiple correct', 'MCC'), ('True or False', 'T/F')], default='Multiple choice', max_length=100)),
                ('question', models.TextField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('answer', models.IntegerField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(blank=True, default=5)),
                ('img', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='pics')),
                ('files', models.FileField(blank=True, max_length=254, upload_to='Quiz/uploads')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('quiznumber', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('Questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.question')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiznumber',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.quiz'),
        ),
    ]
