# Generated by Django 3.1.4 on 2021-01-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_auto_20210128_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
