# Generated by Django 3.1.4 on 2021-01-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_quiz_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Quizname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('Quizname', 'course')},
        ),
    ]
