# Generated by Django 3.1.4 on 2021-01-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_auto_20210130_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiznumber',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='student_question',
            old_name='quiznumber',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
