# Generated by Django 3.1.4 on 2021-01-30 10:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_auto_20210130_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontype', models.CharField(choices=[('Multiple choice', 'MCQ'), ('Multiple correct', 'MCC'), ('True or False', 'T/F')], default='Multiple choice', max_length=100)),
                ('question', models.TextField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('answer', models.IntegerField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(blank=True, default=5)),
                ('img', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='pics')),
                ('files', models.FileField(blank=True, max_length=254, upload_to='Quiz/uploads')),
                ('quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Question',
        ),
    ]
